const colors = ['purple', 'orange', 'green'];
const patterns = ['solid', 'dashed', 'dots'];
const shapes = ['pill', 'chevron', 'diamond'];
const cards = [
  {id: 0, count: [1], color: 0, pattern: 0, shape: 0, selected: false},
  {id: 1, count: [1], color: 0, pattern: 1, shape: 0, selected: false},
  {id: 2, count: [1], color: 0, pattern: 2, shape: 0, selected: false},
  {id: 3, count: [1], color: 1, pattern: 0, shape: 0, selected: false},
  {id: 4, count: [1], color: 1, pattern: 1, shape: 0, selected: false},
  {id: 5, count: [1], color: 1, pattern: 2, shape: 0, selected: false},
  {id: 6, count: [1], color: 2, pattern: 0, shape: 0, selected: false},
  {id: 7, count: [1], color: 2, pattern: 1, shape: 0, selected: false},
  {id: 8, count: [1], color: 2, pattern: 2, shape: 0, selected: false},
  {id: 9, count: [1, 2], color: 0, pattern: 0, shape: 0, selected: false},
  {id: 10, count: [1, 2], color: 0, pattern: 1, shape: 0, selected: false},
  {id: 11, count: [1, 2], color: 0, pattern: 2, shape: 0, selected: false},
  {id: 12, count: [1, 2], color: 1, pattern: 0, shape: 0, selected: false},
  {id: 13, count: [1, 2], color: 1, pattern: 1, shape: 0, selected: false},
  {id: 14, count: [1, 2], color: 1, pattern: 2, shape: 0, selected: false},
  {id: 15, count: [1, 2], color: 2, pattern: 0, shape: 0, selected: false},
  {id: 16, count: [1, 2], color: 2, pattern: 1, shape: 0, selected: false},
  {id: 17, count: [1, 2], color: 2, pattern: 2, shape: 0, selected: false},
  {id: 18, count: [1, 2, 3], color: 0, pattern: 0, shape: 0, selected: false},
  {id: 19, count: [1, 2, 3], color: 0, pattern: 1, shape: 0, selected: false},
  {id: 20, count: [1, 2, 3], color: 0, pattern: 2, shape: 0, selected: false},
  {id: 21, count: [1, 2, 3], color: 1, pattern: 0, shape: 0, selected: false},
  {id: 22, count: [1, 2, 3], color: 1, pattern: 1, shape: 0, selected: false},
  {id: 23, count: [1, 2, 3], color: 1, pattern: 2, shape: 0, selected: false},
  {id: 24, count: [1, 2, 3], color: 2, pattern: 0, shape: 0, selected: false},
  {id: 25, count: [1, 2, 3], color: 2, pattern: 1, shape: 0, selected: false},
  {id: 26, count: [1, 2, 3], color: 2, pattern: 2, shape: 0, selected: false},
  {id: 27, count: [1], color: 0, pattern: 0, shape: 1, selected: false},
  {id: 28, count: [1], color: 0, pattern: 1, shape: 1, selected: false},
  {id: 29, count: [1], color: 0, pattern: 2, shape: 1, selected: false},
  {id: 30, count: [1], color: 1, pattern: 0, shape: 1, selected: false},
  {id: 31, count: [1], color: 1, pattern: 1, shape: 1, selected: false},
  {id: 32, count: [1], color: 1, pattern: 2, shape: 1, selected: false},
  {id: 33, count: [1], color: 2, pattern: 0, shape: 1, selected: false},
  {id: 34, count: [1], color: 2, pattern: 1, shape: 1, selected: false},
  {id: 35, count: [1], color: 2, pattern: 2, shape: 1, selected: false},
  {id: 36, count: [1, 2], color: 0, pattern: 0, shape: 1, selected: false},
  {id: 37, count: [1, 2], color: 0, pattern: 1, shape: 1, selected: false},
  {id: 38, count: [1, 2], color: 0, pattern: 2, shape: 1, selected: false},
  {id: 39, count: [1, 2], color: 1, pattern: 0, shape: 1, selected: false},
  {id: 40, count: [1, 2], color: 1, pattern: 1, shape: 1, selected: false},
  {id: 41, count: [1, 2], color: 1, pattern: 2, shape: 1, selected: false},
  {id: 42, count: [1, 2], color: 2, pattern: 0, shape: 1, selected: false},
  {id: 43, count: [1, 2], color: 2, pattern: 1, shape: 1, selected: false},
  {id: 44, count: [1, 2], color: 2, pattern: 2, shape: 1, selected: false},
  {id: 45, count: [1, 2, 3], color: 0, pattern: 0, shape: 1, selected: false},
  {id: 46, count: [1, 2, 3], color: 0, pattern: 1, shape: 1, selected: false},
  {id: 47, count: [1, 2, 3], color: 0, pattern: 2, shape: 1, selected: false},
  {id: 48, count: [1, 2, 3], color: 1, pattern: 0, shape: 1, selected: false},
  {id: 49, count: [1, 2, 3], color: 1, pattern: 1, shape: 1, selected: false},
  {id: 50, count: [1, 2, 3], color: 1, pattern: 2, shape: 1, selected: false},
  {id: 51, count: [1, 2, 3], color: 2, pattern: 0, shape: 1, selected: false},
  {id: 52, count: [1, 2, 3], color: 2, pattern: 1, shape: 1, selected: false},
  {id: 53, count: [1, 2, 3], color: 2, pattern: 2, shape: 1, selected: false},
  {id: 54, count: [1], color: 0, pattern: 0, shape: 2, selected: false},
  {id: 55, count: [1], color: 0, pattern: 1, shape: 2, selected: false},
  {id: 56, count: [1], color: 0, pattern: 2, shape: 2, selected: false},
  {id: 57, count: [1], color: 1, pattern: 0, shape: 2, selected: false},
  {id: 58, count: [1], color: 1, pattern: 1, shape: 2, selected: false},
  {id: 59, count: [1], color: 1, pattern: 2, shape: 2, selected: false},
  {id: 60, count: [1], color: 2, pattern: 0, shape: 2, selected: false},
  {id: 61, count: [1], color: 2, pattern: 1, shape: 2, selected: false},
  {id: 62, count: [1], color: 2, pattern: 2, shape: 2, selected: false},
  {id: 63, count: [1, 2], color: 0, pattern: 0, shape: 2, selected: false},
  {id: 64, count: [1, 2], color: 0, pattern: 1, shape: 2, selected: false},
  {id: 65, count: [1, 2], color: 0, pattern: 2, shape: 2, selected: false},
  {id: 66, count: [1, 2], color: 1, pattern: 0, shape: 2, selected: false},
  {id: 67, count: [1, 2], color: 1, pattern: 1, shape: 2, selected: false},
  {id: 68, count: [1, 2], color: 1, pattern: 2, shape: 2, selected: false},
  {id: 69, count: [1, 2], color: 2, pattern: 0, shape: 2, selected: false},
  {id: 70, count: [1, 2], color: 2, pattern: 1, shape: 2, selected: false},
  {id: 71, count: [1, 2], color: 2, pattern: 2, shape: 2, selected: false},
  {id: 72, count: [1, 2, 3], color: 0, pattern: 0, shape: 2, selected: false},
  {id: 73, count: [1, 2, 3], color: 0, pattern: 1, shape: 2, selected: false},
  {id: 74, count: [1, 2, 3], color: 0, pattern: 2, shape: 2, selected: false},
  {id: 75, count: [1, 2, 3], color: 1, pattern: 0, shape: 2, selected: false},
  {id: 76, count: [1, 2, 3], color: 1, pattern: 1, shape: 2, selected: false},
  {id: 77, count: [1, 2, 3], color: 1, pattern: 2, shape: 2, selected: false},
  {id: 78, count: [1, 2, 3], color: 2, pattern: 0, shape: 2, selected: false},
  {id: 79, count: [1, 2, 3], color: 2, pattern: 1, shape: 2, selected: false},
  {id: 80, count: [1, 2, 3], color: 2, pattern: 2, shape: 2, selected: false}
];

export {
  cards,
  colors,
  patterns,
  shapes
};
