const colors = ['purple', 'orange', 'green'];
const patterns = ['solid', 'dashed', 'dots'];
const shapes = ['pill', 'chevron', 'diamond'];
const cards = [
  {count: [1], color: 0, pattern: 0, shape: 0},
  {count: [1], color: 0, pattern: 1, shape: 0},
  {count: [1], color: 0, pattern: 2, shape: 0},
  {count: [1], color: 1, pattern: 0, shape: 0},
  {count: [1], color: 1, pattern: 1, shape: 0},
  {count: [1], color: 1, pattern: 2, shape: 0},
  {count: [1], color: 2, pattern: 0, shape: 0},
  {count: [1], color: 2, pattern: 1, shape: 0},
  {count: [1], color: 2, pattern: 2, shape: 0},
  {count: [1, 2], color: 0, pattern: 0, shape: 0},
  {count: [1, 2], color: 0, pattern: 1, shape: 0},
  {count: [1, 2], color: 0, pattern: 2, shape: 0},
  {count: [1, 2], color: 1, pattern: 0, shape: 0},
  {count: [1, 2], color: 1, pattern: 1, shape: 0},
  {count: [1, 2], color: 1, pattern: 2, shape: 0},
  {count: [1, 2], color: 2, pattern: 0, shape: 0},
  {count: [1, 2], color: 2, pattern: 1, shape: 0},
  {count: [1, 2], color: 2, pattern: 2, shape: 0},
  {count: [1, 2, 3], color: 0, pattern: 0, shape: 0},
  {count: [1, 2, 3], color: 0, pattern: 1, shape: 0},
  {count: [1, 2, 3], color: 0, pattern: 2, shape: 0},
  {count: [1, 2, 3], color: 1, pattern: 0, shape: 0},
  {count: [1, 2, 3], color: 1, pattern: 1, shape: 0},
  {count: [1, 2, 3], color: 1, pattern: 2, shape: 0},
  {count: [1, 2, 3], color: 2, pattern: 0, shape: 0},
  {count: [1, 2, 3], color: 2, pattern: 1, shape: 0},
  {count: [1, 2, 3], color: 2, pattern: 2, shape: 0},
  {count: [1], color: 0, pattern: 0, shape: 1},
  {count: [1], color: 0, pattern: 1, shape: 1},
  {count: [1], color: 0, pattern: 2, shape: 1},
  {count: [1], color: 1, pattern: 0, shape: 1},
  {count: [1], color: 1, pattern: 1, shape: 1},
  {count: [1], color: 1, pattern: 2, shape: 1},
  {count: [1], color: 2, pattern: 0, shape: 1},
  {count: [1], color: 2, pattern: 1, shape: 1},
  {count: [1], color: 2, pattern: 2, shape: 1},
  {count: [1, 2], color: 0, pattern: 0, shape: 1},
  {count: [1, 2], color: 0, pattern: 1, shape: 1},
  {count: [1, 2], color: 0, pattern: 2, shape: 1},
  {count: [1, 2], color: 1, pattern: 0, shape: 1},
  {count: [1, 2], color: 1, pattern: 1, shape: 1},
  {count: [1, 2], color: 1, pattern: 2, shape: 1},
  {count: [1, 2], color: 2, pattern: 0, shape: 1},
  {count: [1, 2], color: 2, pattern: 1, shape: 1},
  {count: [1, 2], color: 2, pattern: 2, shape: 1},
  {count: [1, 2, 3], color: 0, pattern: 0, shape: 1},
  {count: [1, 2, 3], color: 0, pattern: 1, shape: 1},
  {count: [1, 2, 3], color: 0, pattern: 2, shape: 1},
  {count: [1, 2, 3], color: 1, pattern: 0, shape: 1},
  {count: [1, 2, 3], color: 1, pattern: 1, shape: 1},
  {count: [1, 2, 3], color: 1, pattern: 2, shape: 1},
  {count: [1, 2, 3], color: 2, pattern: 0, shape: 1},
  {count: [1, 2, 3], color: 2, pattern: 1, shape: 1},
  {count: [1, 2, 3], color: 2, pattern: 2, shape: 1},
  {count: [1], color: 0, pattern: 0, shape: 2},
  {count: [1], color: 0, pattern: 1, shape: 2},
  {count: [1], color: 0, pattern: 2, shape: 2},
  {count: [1], color: 1, pattern: 0, shape: 2},
  {count: [1], color: 1, pattern: 1, shape: 2},
  {count: [1], color: 1, pattern: 2, shape: 2},
  {count: [1], color: 2, pattern: 0, shape: 2},
  {count: [1], color: 2, pattern: 1, shape: 2},
  {count: [1], color: 2, pattern: 2, shape: 2},
  {count: [1, 2], color: 0, pattern: 0, shape: 2},
  {count: [1, 2], color: 0, pattern: 1, shape: 2},
  {count: [1, 2], color: 0, pattern: 2, shape: 2},
  {count: [1, 2], color: 1, pattern: 0, shape: 2},
  {count: [1, 2], color: 1, pattern: 1, shape: 2},
  {count: [1, 2], color: 1, pattern: 2, shape: 2},
  {count: [1, 2], color: 2, pattern: 0, shape: 2},
  {count: [1, 2], color: 2, pattern: 1, shape: 2},
  {count: [1, 2], color: 2, pattern: 2, shape: 2},
  {count: [1, 2, 3], color: 0, pattern: 0, shape: 2},
  {count: [1, 2, 3], color: 0, pattern: 1, shape: 2},
  {count: [1, 2, 3], color: 0, pattern: 2, shape: 2},
  {count: [1, 2, 3], color: 1, pattern: 0, shape: 2},
  {count: [1, 2, 3], color: 1, pattern: 1, shape: 2},
  {count: [1, 2, 3], color: 1, pattern: 2, shape: 2},
  {count: [1, 2, 3], color: 2, pattern: 0, shape: 2},
  {count: [1, 2, 3], color: 2, pattern: 1, shape: 2},
  {count: [1, 2, 3], color: 2, pattern: 2, shape: 2}
];

export {
  cards,
  colors,
  patterns,
  shapes
};
